name: Sysdig CI Scan

on:
  push:
    branches:
      - main
      - ci/sysdig-integration
  pull_request:
    branches:
      - main
      - ci/sysdig-integration

jobs:
  scan:
    name: Sysdig Scan Docker + IaC (with docker.sock)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build vote image
        run: |
          docker build -t vote-image ./vote
          docker tag vote-image vote-image:ci

      - name: Scan Docker image using docker.sock
        run: |
          docker run --rm             -v /var/run/docker.sock:/var/run/docker.sock             -e SECURE_API_TOKEN=${{ secrets.SYSDIG_SECURE_TOKEN }}             quay.io/sysdig/sysdig-cli-scanner:latest             --apiurl ${{ secrets.SYSDIG_API_URL }}             vote-image:ci

      - name: Scan IaC (k8s-specifications)
        run: |
          docker run --rm             -e SECURE_API_TOKEN=${{ secrets.SYSDIG_SECURE_TOKEN }}             -v ${{ github.workspace }}:/iac             quay.io/sysdig/sysdig-cli-scanner:latest             --apiurl ${{ secrets.SYSDIG_API_URL }}             --iac scan /iac/k8s-specifications
