name: Sysdig CI Scan

on:
  pull_request:
    branches:
      - main
      - ci/sysdig-integration
  push:
    branches:
      - main
      - ci/sysdig-integration

jobs:
  scan:
    name: Sysdig Scan Docker + IaC
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build vote image
      run: |
        docker build -t vote-image ./vote
        docker save vote-image -o vote-image.tar

    - name: Scan Docker image with Sysdig
      run: |
        docker run --rm \
          -e SECURE_API_TOKEN=${{ secrets.SYSDIG_SECURE_TOKEN }} \
          -v ${{ github.workspace }}/vote-image.tar:/tmp/vote-image.tar \
          quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
          --apiurl ${{ secrets.SYSDIG_API_URL }} \
          --image-archive /tmp/vote-image.tar

    - name: Scan IaC (k8s-specifications)
      run: |
        docker run --rm \
          -e SECURE_API_TOKEN=${{ secrets.SYSDIG_SECURE_TOKEN }} \
          -v ${{ github.workspace }}:/iac \
          quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
          --apiurl ${{ secrets.SYSDIG_API_URL }} \
          --iac scan /iac/k8s-specifications
