name: Sysdig Scan (Official Action)

on:
  push:
    branches:
      - main
      - ci/sysdig-integration
  pull_request:
    branches:
      - main
      - ci/sysdig-integration

jobs:
  scan:
    name: Docker + IaC Scan via Sysdig Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build vote Docker image
        run: |
          docker build ./vote -t vote-app:${{ github.sha }}

      - name: Scan vote image with Sysdig
        uses: sysdiglabs/scan-action@v6
        with:
          image-tag: vote-app:${{ github.sha }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_API_URL }}
          stop-on-processing-error: true

      - name: Scan Kubernetes IaC manifests
        uses: sysdiglabs/scan-action@v6
        with:
          mode: iac
          cli-scanner-version: 1.24.2
          iac-scan-path: k8s-specifications
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_API_URL }}
          stop-on-processing-error: true
