name: Sysdig CI Scan

on:
  push:
    branches:
      - main
      - ci/sysdig-integration
  pull_request:
    branches:
      - main
      - ci/sysdig-integration

jobs:
  scan:
    name: Sysdig Scan Docker + IaC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build vote image
        run: |
          docker build -t vote-image ./vote
          docker save vote-image -o vote-image.tar

      - name: Download Sysdig CLI Scanner
        run: |
          curl -LO https://download.sysdig.com/scanning/sysdig-cli-scanner/latest/linux/sysdig-cli-scanner
          chmod +x sysdig-cli-scanner

      - name: Scan Docker image from archive with Sysdig (binary)
        run: |
          ./sysdig-cli-scanner             --standalone             --input-file vote-image.tar             vote-image:ci             --console-log             --detailed-policies-eval             --full-vulns-table             -e SECURE_API_TOKEN=${{ secrets.SYSDIG_SECURE_TOKEN }}

      - name: Scan IaC (k8s-specifications)
        run: |
          ./sysdig-cli-scanner             --apiurl ${{ secrets.SYSDIG_API_URL }}             --iac scan ./k8s-specifications             -e SECURE_API_TOKEN=${{ secrets.SYSDIG_SECURE_TOKEN }}
